# Generated by Django 4.2.3 on 2023-08-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.CharField(choices=[('flexible', 'flexible'), ('evenings', 'evenings'), ('mornings', 'mornings'), ('weekends', 'weekends'), ('not_currently_available', 'currently unavailable but pop me on the list'), ('busy', 'busy'), ('unavailable', 'unavailable')], default='flexible', max_length=200),
            preserve_default=False,
        ),
    ]
