# Generated by Django 4.2.3 on 2023-07-29 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='s_open',
            new_name='is_open',
        ),
    ]
